# Exported from Render on 2024-10-31T12:22:14Z
services:
- type: web
  name: quartz-status
  runtime: node
  repo: https://github.com/openclimatefix/quartz-status
  plan: starter
  envVars:
  - key: SERVER_URL
    sync: false
  - key: AUTH0_AUDIENCE
    sync: false
  - key: AUTH0_CLIENT_SECRET
    sync: false
  - key: AUTH0_CLIENT_ID
    sync: false
  - key: AUTH0_ISSUER_BASE_URL
    sync: false
  - key: AUTH0_DOMAIN
    sync: false
  - key: UK_PV_SITE_API_URL
    sync: false
  - key: UK_PV_NATIONAL_API_URL
    sync: false
  region: oregon
  buildCommand: yarn --frozen-lockfile install
  startCommand: yarn start
  healthCheckPath: /health
  domains:
  - status-dev.quartz.energy
  - status.quartz.energy
  previews:
    generation: manual
version: "1"
